version: '3.8'
services:

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./appdata/config:/config
    ports:
      - 5055:5055
    restart: unless-stopped


  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./data:/config
      - .movies:/movies #optional
      - .downloadclient-downloads:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped


  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./data:/config
      - ./tvseries:/tv #optional
      - ./downloadclient-downloads:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped


  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ./data:/config
    ports:
      - 9696:9696
    restart: unless-stopped
